spring.application.name=k8s-config-secret-map-example
server.port=8080

my.project.first.config.property=${configFirstProperty:default-first-config}
my.project.second.config.property=${configSecondProperty:default-second-config}
my.project.first.secret=${secretFirstKey:default-first-secret}
my.project.second.secret=${secretSecondKey:default-second-secret}
